spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  application:
    name: acquiring-mock-backend
  datasource:
    url: "jdbc:postgresql://193.222.62.125:5432/${spring.application.name}"
    driver-class-name: org.postgresql.Driver
    username: "user"
    password: "mypassword"

jwt:
  lifetime: 30

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        stat: DEBUG
    springframework:
      jdbc:
        datasource:
          init: DEBUG